spring.application.name=api


# Configurações do Admin Padrão
# O formato ${VARIAVEL:valor_padrao} permite ter um valor reserva, 
# mas não vamos colocar a senha padrão aqui!
app.admin.email=${ADMIN_EMAIL:jaokrito@gmail.com}
app.admin.senha=${ADMIN_PASSWORD: senha123}
#Secret key
api.security.token.secret= SecretKEY;

# Conexão com o PostgreSQL local do computador
spring.datasource.url=jdbc:postgresql://localhost:5432
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# DESATIVA o controle dinâmico de portas do Spring Boot Docker Compose
#spring.docker.compose.lifecycle-management=none

# Opcional: ajuda a criar ou atualizar as tabelas automaticamente no início
# Configuração do Hibernate para atualizar o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JPA / Hibernate - Atualiza a estrutura de tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

