services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=BotecoDoHudson_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'ADMIN_PASSWORD=${ADMIN_PASSWORD}'
    ports:
      - '5433:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
